# Generated by Django 5.2.6 on 2026-01-20 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firebase_uid",
                    models.CharField(
                        db_index=True,
                        help_text="Firebase Authentication UID",
                        max_length=128,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("photo_url", models.URLField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("teacher", "Teacher"),
                            ("admin", "Admin"),
                            ("mentor", "Mentor"),
                        ],
                        default="teacher",
                        max_length=20,
                    ),
                ),
                ("school", models.CharField(blank=True, max_length=255, null=True)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "grades_taught",
                    models.CharField(
                        blank=True,
                        help_text="Classes taught, e.g., '5,6,7' or 'Class 5-8'",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "subjects_taught",
                    models.CharField(
                        blank=True,
                        help_text="Subjects taught, e.g., 'Mathematics,Science'",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "number_of_students",
                    models.PositiveIntegerField(
                        default=0, help_text="Total students in classes"
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        default="hi",
                        help_text="Preferred language code (hi, en, etc.)",
                        max_length=10,
                    ),
                ),
                ("fcm_token", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Link to Django User for future migration",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "user_profiles",
            },
        ),
        migrations.CreateModel(
            name="TeacherStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_sos_requests", models.PositiveIntegerField(default=0)),
                ("strategies_used", models.PositiveIntegerField(default=0)),
                ("strategies_rated", models.PositiveIntegerField(default=0)),
                ("positive_ratings", models.PositiveIntegerField(default=0)),
                ("current_streak_days", models.PositiveIntegerField(default=0)),
                ("max_streak_days", models.PositiveIntegerField(default=0)),
                ("last_active_date", models.DateField(blank=True, null=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="api.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Stats",
                "verbose_name_plural": "Teacher Stats",
                "db_table": "teacher_stats",
            },
        ),
    ]
