# Generated by Django 5.2.6 on 2026-01-20 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("title_hi", models.CharField(blank=True, max_length=255, null=True)),
                ("content", models.TextField(help_text="Full strategy content")),
                ("subject", models.CharField(blank=True, max_length=100, null=True)),
                ("grade", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_strategies",
                        to="api.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "saved_strategies",
                "ordering": ["-created_at"],
            },
        ),
    ]
