# Generated by Django 5.2.6 on 2026-01-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_savedstrategy"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedstrategy",
            name="video_url",
            field=models.URLField(
                blank=True, help_text="YouTube video URL if available", null=True
            ),
        ),
    ]
