# Generated by Django 5.2.6 on 2026-01-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_savedstrategy_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedstrategy",
            name="is_public",
            field=models.BooleanField(default=True, help_text="Visible in shared feed"),
        ),
        migrations.AddField(
            model_name="savedstrategy",
            name="likes_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="savedstrategy",
            name="saves_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
