# Generated by Django 5.2.6 on 2026-01-20 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_savedstrategy_is_public_savedstrategy_likes_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedstrategy",
            name="group_id",
            field=models.UUIDField(
                blank=True,
                help_text="ID to group strategies from same SOS response",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="StrategyInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_liked", models.BooleanField(default=False)),
                ("is_saved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="api.savedstrategy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="api.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "strategy_interactions",
                "unique_together": {("user", "strategy")},
            },
        ),
    ]
