# Generated by Django 5.2.6 on 2026-01-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_savedstrategy_group_id_strategyinteraction"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedstrategy",
            name="resource_type",
            field=models.CharField(
                choices=[("strategy", "Teaching Strategy"), ("snap", "Snap Solution")],
                default="strategy",
                help_text="Type of saved resource",
                max_length=20,
            ),
        ),
    ]
