# Generated by Django 5.2.6 on 2026-02-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_savedstrategy_resource_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedstrategy",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("strategy", "Teaching Strategy"),
                    ("snap", "Snap Solution"),
                    ("pdf", "PDF Resource"),
                ],
                default="strategy",
                help_text="Type of saved resource",
                max_length=20,
            ),
        ),
    ]
