// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxmCMdT5UOcWTKDpsFkoJqOBQO2Ybp8dU',
    appId: '1:724170416520:web:98b64da94f2a8f3b3d1a3d',
    messagingSenderId: '724170416520',
    projectId: 'sikshasathi-6c10b',
    authDomain: 'sikshasathi-6c10b.firebaseapp.com',
    storageBucket: 'sikshasathi-6c10b.firebasestorage.app',
    measurementId: 'G-V4BXCGDRGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDch2PDrWSU0CCqP10imuMfgnQtPcJI1Q8',
    appId: '1:724170416520:android:25a69df9de5cc1513d1a3d',
    messagingSenderId: '724170416520',
    projectId: 'sikshasathi-6c10b',
    storageBucket: 'sikshasathi-6c10b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTngSAsvwVaBKJr54fy0dbeWEfrk5E7dM',
    appId: '1:724170416520:ios:76f281b4752ea9133d1a3d',
    messagingSenderId: '724170416520',
    projectId: 'sikshasathi-6c10b',
    storageBucket: 'sikshasathi-6c10b.firebasestorage.app',
    iosBundleId: 'com.sikshasathi.app',
  );
}
